- name: Ensure Administrator is part of Domain Admins
  microsoft.ad.group:
    name: "Domain Admins"
    members:
      add:
        - Administrator
    state: present

- name: organisation units
  import_tasks: ou.yml

- name: groups
  import_tasks: groups.yml

- name: users
  import_tasks: users.yml

# Managed BY
- name: Assign managed_by domainlocal groups
  microsoft.ad.group:
    name: "{{ item.key }}"
    managed_by: "{{ item.value.managed_by }}"
    state: present
    scope: domainlocal
  with_dict: "{{ ad_groups['domainlocal'] }}"
  when: ad_groups['domainlocal'] is defined and item.value.managed_by is defined

- name: Assign managed_by universal groups
  microsoft.ad.group:
    name: "{{ item.key }}"
    managed_by: "{{ item.value.managed_by }}"
    state: present
    scope: universal
  with_dict: "{{ ad_groups['universal'] }}"
  when: ad_groups['universal'] is defined and item.value.managed_by is defined

- name: Assign managed_by global groups
  microsoft.ad.group:
    name: "{{ item.key }}"
    managed_by: "{{ item.value.managed_by }}"
    state: present
    scope: global
  with_dict: "{{ ad_groups['global'] }}"
  when: ad_groups['global'] is defined and item.value.managed_by is defined

# Add members
- name: Add members to the Universal group, preserving existing membership
  microsoft.ad.group:
    name: "{{ item.key }}"
    members:
      add:
        - "{{ item.value.members }}"
  with_dict: "{{ ad_groups['universal'] }}"
  when: ad_groups['universal'] is defined and item.value.members is defined

- name: Add members to the Global group, preserving existing membership
  microsoft.ad.group:
    name: "{{ item.key }}"
    members:
      add:
        - "{{ item.value.members }}"
  with_dict: "{{ ad_groups['global'] }}"
  when: ad_groups['global'] is defined and item.value.members is defined

- name: Add members to the Domainlocal group, preserving existing membership
  microsoft.ad.group:
    name: "{{ item.key }}"
    members:
      add:
        - "{{ item.value.members }}"
  with_dict: "{{ ad_groups['domainlocal'] }}"
  when: ad_groups['domainlocal'] is defined and item.value.members is defined
